version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    container_name: products-catalog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: catalog
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
volumes:
  database: